pipeline {
  agent any

  tools {
    jdk 'JAVA_HOME'
    maven 'M2_HOME'
  }

  environment {
    GIT_CREDENTIALS_ID       = '14409463'
    GIT_BRANCH               = 'main'
    GIT_URL                  = 'https://github.com/koussayAttia/student-management.git'

    DOCKERHUB_REPO           = 'koussaybenattia/student-management'
    DOCKERHUB_CREDENTIALS_ID = 'efb9d575-c792-451d-8397-39d6121e21ba'

    // Valeur par défaut (sera écrasée automatiquement après minikube service --url)
    SONAR_HOST_URL           = 'http://localhost:9000'
    SONAR_TOKEN_CRED_ID      = '123456789'
  }

  stages {
    stage('Checkout') {
      steps {
        git branch: env.GIT_BRANCH, url: env.GIT_URL, credentialsId: env.GIT_CREDENTIALS_ID
      }
    }

    stage('Build (clean & package, sans tests)') {
      steps {
        dir('student-management') {
          sh 'mvn clean package -DskipTests'
        }
      }
    }

    stage('Deploy Infra (MySQL + SonarQube)') {
        steps {
          dir('student-management') {
            sh '''
              set -eux
      
              kubectl  get namespace devops || kubectl  create namespace devops
      
              kubectl  apply -f mysql-deployment.yaml -n devops
              kubectl  apply -f sonarqube-deployment.yaml -n devops
      
              kubectl  rollout status deployment/sonarqube -n devops --timeout=900s
      
              SONAR_URL=$(minikube service sonarqube-service -n devops --url | head -n 1)
              echo "SONAR_HOST_URL=$SONAR_URL" > sonar_url.env
            '''
            script {
              env.SONAR_HOST_URL = readFile('sonar_url.env').trim().split('=')[1]
            }
          }
        }
      }
    stage('Build Docker Image') {
      steps {
        dir('student-management') {
          sh 'docker build -t $DOCKERHUB_REPO:$BUILD_NUMBER .'
        }
      }
    }

    stage('Push Docker Image to Docker Hub') {
      steps {
        withCredentials([usernamePassword(
          credentialsId: env.DOCKERHUB_CREDENTIALS_ID,
          usernameVariable: 'DOCKERHUB_USER',
          passwordVariable: 'DOCKERHUB_PASS'
        )]) {
          sh '''
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USER" --password-stdin
            docker push $DOCKERHUB_REPO:$BUILD_NUMBER
          '''
        }
      }
    }

    stage('Deploy to Kubernetes') {
      steps {
        dir('student-management') {
          sh '''
            set -eux
            # NE PAS delete/start minikube ici !
            minikube kubectl -- apply -f spring-deployment.yaml -n devops
            minikube kubectl -- get pods -n devops
          '''
        }
      }
    }
  }
}
